### ISSUE TITLE
Ideally at some point : get rid of the hack for mysql conf

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/civicrm_drupal7_ynh#27]
Just noticed while scrolling the tests that: 

```
177825 ERROR Packagers /!\ This app manually modified some system configuration files! This should not happen! If you need to do so, you should implement a proper conf_regen hook. Those configuration were affected:
    - /etc/mysql/my.cnf
```

This comes from : 

```
ynh_replace_string --match_string="thread_stack = 128K" --replace_string="thread_stack = 192K" --target_file="/etc/mysql/my.cnf"
```

People will get a warning in their diagnosis about it and will probably revert the change if they don't understand it ... The proper way to handle this is to add a regen conf hook but meh, it sounds overkill for such a small change so I don't know what to do

**Comment by yalh76** [comment]
I have to do a hook one day ^^
