### ISSUE TITLE
Drupal 7 EOL

### ISSUE THREAD

**Issue by derDieDasJojo** [YunoHost-Apps/civicrm_drupal7_ynh#71]
Drupal 7 will soon reach its final End of Life: https://endoflife.date/drupal
Are there Any plans to release a Version based on Backdrop (Drupal 7 Fork) or Drupal 10?

**Comment by yalh76** [comment]
There is already :

- https://github.com/YunoHost-Apps/backdrop_ynh
- https://github.com/YunoHost-Apps/drupal_ynh
